# A100-Optimized YOLOv5 ControlNet Training Configuration

# Data paths
data:
  preprocessed_dir: "/home/jovyan/p.kudrevatyh/bg_subtraction"
  annotations_dir: "/home/jovyan/p.kudrevatyh/yolov5_motion/data/annotations"
  splits_file: "/home/jovyan/p.kudrevatyh/yolov5_motion/data/splits.json"
  output_dir: "./a100_training_outputs"

# Model configuration
model:
  yolo_weights: "/home/jovyan/p.kudrevatyh/yolov5m.pt"
  controlnet_weights: null
  yolo_cfg: "/home/jovyan/p.kudrevatyh/yolov5/models/yolov5m.yaml"
  img_size: 640
  num_classes: 1
  train_all: false
  train_controlnet: true
  train_head: true

# Training parameters optimized for A100
training:
  epochs: 100
  # A100 can handle larger batch sizes
  batch_size: 64  
  val_batch_size: 128
  # More workers for faster data loading
  workers: 12     
  val_ratio: 0.1
  
  # Prodigy works well with large batch sizes on A100
  optimizer: "prodigy"  
  lr: 1.0
  weight_decay: 0.01
  momentum: 0.937
  
  # Loss weights
  loss:
    box_weight: 0.0539
    obj_weight: 0.632  # obj loss gain
    cls_weight: 0.299
  
  # BF16 precision is optimal for A100
  precision: "bf16"
  
  # Checkpointing
  save_interval: 10
  log_interval: 50    # Less frequent logging for faster training
  eval_interval: 1
  
  # Resume training
  resume: null

  detection:
    conf_thres: 0.25
    iou_thres: 0.45
    max_det: 1000

  augment: true
  augment_prob: 0.5